# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/tamiroffen/Documents/Winter 2020 - Sem 2/Matam/HW/hw3/code_github/FunctionCaller"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/tamiroffen/Documents/Winter 2020 - Sem 2/Matam/HW/hw3/code_github/FunctionCaller"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/tamiroffen/Documents/Winter 2020 - Sem 2/Matam/HW/hw3/code_github/FunctionCaller/CMakeFiles" "/Users/tamiroffen/Documents/Winter 2020 - Sem 2/Matam/HW/hw3/code_github/FunctionCaller//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/tamiroffen/Documents/Winter 2020 - Sem 2/Matam/HW/hw3/code_github/FunctionCaller/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

AdamTestC.o: AdamTestC.cpp.o

.PHONY : AdamTestC.o

# target to build an object file
AdamTestC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/AdamTestC.cpp.o
.PHONY : AdamTestC.cpp.o

AdamTestC.i: AdamTestC.cpp.i

.PHONY : AdamTestC.i

# target to preprocess a source file
AdamTestC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/AdamTestC.cpp.i
.PHONY : AdamTestC.cpp.i

AdamTestC.s: AdamTestC.cpp.s

.PHONY : AdamTestC.s

# target to generate assembly for a file
AdamTestC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/AdamTestC.cpp.s
.PHONY : AdamTestC.cpp.s

partA/date.o: partA/date.cpp.o

.PHONY : partA/date.o

# target to build an object file
partA/date.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partA/date.cpp.o
.PHONY : partA/date.cpp.o

partA/date.i: partA/date.cpp.i

.PHONY : partA/date.i

# target to preprocess a source file
partA/date.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partA/date.cpp.i
.PHONY : partA/date.cpp.i

partA/date.s: partA/date.cpp.s

.PHONY : partA/date.s

# target to generate assembly for a file
partA/date.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partA/date.cpp.s
.PHONY : partA/date.cpp.s

partA/date_wrap.o: partA/date_wrap.cpp.o

.PHONY : partA/date_wrap.o

# target to build an object file
partA/date_wrap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partA/date_wrap.cpp.o
.PHONY : partA/date_wrap.cpp.o

partA/date_wrap.i: partA/date_wrap.cpp.i

.PHONY : partA/date_wrap.i

# target to preprocess a source file
partA/date_wrap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partA/date_wrap.cpp.i
.PHONY : partA/date_wrap.cpp.i

partA/date_wrap.s: partA/date_wrap.cpp.s

.PHONY : partA/date_wrap.s

# target to generate assembly for a file
partA/date_wrap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partA/date_wrap.cpp.s
.PHONY : partA/date_wrap.cpp.s

partB/base_event.o: partB/base_event.cpp.o

.PHONY : partB/base_event.o

# target to build an object file
partB/base_event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partB/base_event.cpp.o
.PHONY : partB/base_event.cpp.o

partB/base_event.i: partB/base_event.cpp.i

.PHONY : partB/base_event.i

# target to preprocess a source file
partB/base_event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partB/base_event.cpp.i
.PHONY : partB/base_event.cpp.i

partB/base_event.s: partB/base_event.cpp.s

.PHONY : partB/base_event.s

# target to generate assembly for a file
partB/base_event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partB/base_event.cpp.s
.PHONY : partB/base_event.cpp.s

partB/closed_event.o: partB/closed_event.cpp.o

.PHONY : partB/closed_event.o

# target to build an object file
partB/closed_event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partB/closed_event.cpp.o
.PHONY : partB/closed_event.cpp.o

partB/closed_event.i: partB/closed_event.cpp.i

.PHONY : partB/closed_event.i

# target to preprocess a source file
partB/closed_event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partB/closed_event.cpp.i
.PHONY : partB/closed_event.cpp.i

partB/closed_event.s: partB/closed_event.cpp.s

.PHONY : partB/closed_event.s

# target to generate assembly for a file
partB/closed_event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partB/closed_event.cpp.s
.PHONY : partB/closed_event.cpp.s

partB/event_container.o: partB/event_container.cpp.o

.PHONY : partB/event_container.o

# target to build an object file
partB/event_container.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partB/event_container.cpp.o
.PHONY : partB/event_container.cpp.o

partB/event_container.i: partB/event_container.cpp.i

.PHONY : partB/event_container.i

# target to preprocess a source file
partB/event_container.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partB/event_container.cpp.i
.PHONY : partB/event_container.cpp.i

partB/event_container.s: partB/event_container.cpp.s

.PHONY : partB/event_container.s

# target to generate assembly for a file
partB/event_container.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partB/event_container.cpp.s
.PHONY : partB/event_container.cpp.s

partB/festival.o: partB/festival.cpp.o

.PHONY : partB/festival.o

# target to build an object file
partB/festival.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partB/festival.cpp.o
.PHONY : partB/festival.cpp.o

partB/festival.i: partB/festival.cpp.i

.PHONY : partB/festival.i

# target to preprocess a source file
partB/festival.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partB/festival.cpp.i
.PHONY : partB/festival.cpp.i

partB/festival.s: partB/festival.cpp.s

.PHONY : partB/festival.s

# target to generate assembly for a file
partB/festival.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partB/festival.cpp.s
.PHONY : partB/festival.cpp.s

partB/open_event.o: partB/open_event.cpp.o

.PHONY : partB/open_event.o

# target to build an object file
partB/open_event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partB/open_event.cpp.o
.PHONY : partB/open_event.cpp.o

partB/open_event.i: partB/open_event.cpp.i

.PHONY : partB/open_event.i

# target to preprocess a source file
partB/open_event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partB/open_event.cpp.i
.PHONY : partB/open_event.cpp.i

partB/open_event.s: partB/open_event.cpp.s

.PHONY : partB/open_event.s

# target to generate assembly for a file
partB/open_event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partB/open_event.cpp.s
.PHONY : partB/open_event.cpp.s

partC/schedule.o: partC/schedule.cpp.o

.PHONY : partC/schedule.o

# target to build an object file
partC/schedule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partC/schedule.cpp.o
.PHONY : partC/schedule.cpp.o

partC/schedule.i: partC/schedule.cpp.i

.PHONY : partC/schedule.i

# target to preprocess a source file
partC/schedule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partC/schedule.cpp.i
.PHONY : partC/schedule.cpp.i

partC/schedule.s: partC/schedule.cpp.s

.PHONY : partC/schedule.s

# target to generate assembly for a file
partC/schedule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/partC/schedule.cpp.s
.PHONY : partC/schedule.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... app"
	@echo "... AdamTestC.o"
	@echo "... AdamTestC.i"
	@echo "... AdamTestC.s"
	@echo "... partA/date.o"
	@echo "... partA/date.i"
	@echo "... partA/date.s"
	@echo "... partA/date_wrap.o"
	@echo "... partA/date_wrap.i"
	@echo "... partA/date_wrap.s"
	@echo "... partB/base_event.o"
	@echo "... partB/base_event.i"
	@echo "... partB/base_event.s"
	@echo "... partB/closed_event.o"
	@echo "... partB/closed_event.i"
	@echo "... partB/closed_event.s"
	@echo "... partB/event_container.o"
	@echo "... partB/event_container.i"
	@echo "... partB/event_container.s"
	@echo "... partB/festival.o"
	@echo "... partB/festival.i"
	@echo "... partB/festival.s"
	@echo "... partB/open_event.o"
	@echo "... partB/open_event.i"
	@echo "... partB/open_event.s"
	@echo "... partC/schedule.o"
	@echo "... partC/schedule.i"
	@echo "... partC/schedule.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

